In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1=[4,5,6,7,'sandip',345.564,True]

In [5]:
np.array(l1)

array(['4', '5', '6', '7', 'sandip', '345.564', 'True'], dtype='<U32')

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.array([[1,2,3],[5,6,7],[8,9,10]])

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns



In [10]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68734 sha256=b2af6d7f154131ba224b03485954861f765ff7b789e14bfb34bd97d14eda6c61
  Stored in directory: c:\users\0038ig744\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks
